# Generated by Django 4.2.5 on 2023-10-02 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('option_equal', 'option_equal'), ('option_not_equal', 'option_not_equal'), ('number_lt', 'number_lt'), ('number_lte', 'number_lte'), ('number_gt', 'number_gt'), ('number_gte', 'number_gte'), ('text_contain', 'text_contain'), ('text_not_contain', 'text_not_contain'), ('text_start', 'text_start'), ('text_not_start', 'text_not_start'), ('text_end', 'text_end'), ('text_not_end', 'text_not_end')], max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnsweredToSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('option', 'option'), ('text', 'text'), ('numerical', 'numerical')], max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Operatior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('and_operator', 'and_operator'), ('or_operator', 'or_operator'), ('xor_operator', 'xor_operator')], max_length=20)),
                ('priority', models.IntegerField()),
                ('first_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_condition', to='survey.condition')),
                ('second_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_condition', to='survey.condition')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='source_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_question', to='survey.question'),
        ),
        migrations.AddField(
            model_name='condition',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='condition',
            name='target_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_question', to='survey.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
